config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get "/", to: "pages#home", as: "root"
  
  get "/pages/donated", to: "pages#donated"

  get "/listings", to: "listings#index", as: "listings"

  get "/listings/new", to: "listings#new", as: "new_listing"

  post "/listings", to: "listings#create"

  get "/listings/:id", to: "listings#show", as: "listing"

  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"

  put "/listings/:id", to: "listings#update"

  patch "/listings/:id", to: "listings#update"

  delete "/listings/:id", to: "listings#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  #the listing NEEDS to have those 3 params
  validates :title, :description, :price, presence:true
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# We're going to specify that the user can have many listings
# if the user gets deleted all their listings will get destroyed
has_many :listings, dependent: :destroy



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_users_listing, only: [:edit, :update, :destroy]

    def index
        @listings = Listing.all
        generate_stripe_session
    end
    
    def new
        @listing = Listing.new
    end

    def create
        @listing = current_user.listings.create(listing_params)
        rerender_if_error("new")
    end

    def edit 
        if @listing
            render("edit")
        else  
            redirect_to listings_path
        end
    end

    def update
        if @listing
            @listing.update(listing_params)
            rerender_if_error("edit")
        else 
            redirect_to listings_path
        end
    end

    def show
        @listing = Listing.find(params["id"])
    end

    def destroy
        if @listing
            @listing.destroy
        end
        redirect_to listings_path
    end


    private
    def listing_params
        params.require(:listing).permit(:title, :price, :description, :picture)
    end

    def generate_stripe_session
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: "Donate to BookShop",
                currency: 'aud',
                quantity: 1,
                amount: 200
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                }
            },
            success_url: "#{root_url}pages/donated?userId=#{current_user.id}",
            cancel_url: "#{root_url}"
        )

        @session_id = session.id
    end

    def rerender_if_error(template_name)
        if @listing.errors.any?
            render template_name
        else
            redirect_to listings_path
        end
    end

    def get_users_listing
        @listing = current_user.listings.find_by_id(params["id"])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    #add action, the name of the action in this case is home
    def home

    end

    def donated
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
  <div class="topnav">
            <a class="active"><%= link_to "BookShop", root_path, class:"navbar-brand" %></a>

            
            <% if user_signed_in? %>
                <a><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
            <% else %>
            <a><%= link_to "Sign Up", new_user_registration_path %></a>	
                <a><%= link_to "Log In", new_user_session_path %></a>
            <% end %>

            <% if user_signed_in? %>
            <a><%= link_to 'Books', listings_path %></a>
            <a><%= link_to 'Add Book', new_listing_path %></a>
            <% end %>
    </div>
          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
         <%= render partial: "layouts/header" %>
          
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookShop
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/header"
    .hero
      .hero-body
        .columns
          .column.is-half.is-offset-one-quarter
            .has-text-centered.mb20
              %h1.title.is-1.title-header
                = link_to "BookShop", listings_path
            .card
              .card-content
                = yield

app/views/listings/_form.html.erb
<div class=form-container>
<h1> Add Book </h1>
<br/>
<%# display errors to user %>
<% if listing.errors.any? %>
    <ul>
        <% listing.errors.full_messages.each do |error| %>
            <li> <%= error %> </li>
        <%end %>
    </ul>
<% end %>


<%= form_with model: listing, local: true do |form| %>

<div class="form-input">
    <%= form.label :title %>
    <%= form.text_field :title, value: listing.title %>
</div>


<div class="form-input">
    <%= form.label :price %>
    <%= form.number_field :price, value: listing.price, min: 0 %>
</div>

<div class="form-input">
    <%= form.label :description %>
    <%= form.text_area :description, value: listing.description %>
</div>


<div class="form-input">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: "image/png, image/gif, image/jpeg,
    image/jpg" %>
</div>

<div>
    <%= form.submit "Add Book" %>
</div>

<% end %>

</div>

app/views/listings/edit.html.erb
<%= render "form", listing: @listing %>

app/views/listings/index.html.erb
<div class="donate">
  <p>Please help the shop</p>

  <button data-stripe="donate">Donate $2</button>

</div>
<br/>
<br/>
<br/>
<%# the best way to access some information from the controller
inside the view is to use an instance variables 
eg. @listing %>
<h1>Books Catalogue</h1>
<div class="listings-container">
<ul>
  
  <br/>
    <% for listing in @listings %>
    <li>
        <%= link_to "#{listing.title} - #{number_to_currency(listing.price)}",
         listing_path(listing.id) %>
    </li>
    <% end %>
</ul>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
  document
    .querySelector("[data-stripe='donate']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/listings/new.html.erb
<%= render "form", listing: @listing %>

app/views/listings/show.html.erb
<div class="container">
<h1><%= @listing.title %></h1>
<br/>
<% if @listing.picture.attached? %>
    <%= image_tag  @listing.picture, style: "width: 200px"%>
<% end %>
<br />
<%= number_to_currency(@listing.price) %>
<br/>
<p class="contact">
Seller's email: <strong><%= @listing.user.email %></strong>
</p>
<br/>

<% if current_user.id == @listing.user.id %>

    <%= link_to "Edit Book", edit_listing_path(@listing.id) %>
   
    <%= form_with model: @listing, local: true, method: "delete" do |form| %>
        <%= submit_tag "Delete Book" %>
    <% end %>
<% end %>
<br/>


<p>
    <%= @listing.description %>
</p>
</div>

app/views/pages/donated.html.erb
<p class="thanks"> Thanks for donating! &#128525;</h1>

app/views/pages/home.html.erb
<h2>BookShop</h2>
<br/>
<p class="welcome">We have a new and used books</p>
<p class="welcome">Where second hand books find a new home</p>
<br/>

<p class="imagen"><%= image_tag 'books.jpg' %></p>